UPDATE app2.js:  WORKING, breaks at threads, I think:
- ERROR:

  TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator)

- NEXT: add null object check like

  object !== null && object !== undefined

  OR

  const isObject = (value) => typeof value === "object" && value !== null

https://levelup.gitconnected.com/how-to-check-for-an-object-in-javascript-object-null-check-3b2632330296